config/routes.rb
Mapaddr::Application.routes.draw do

  resource :session, only: [:create, :destroy]

  resources :users, except: [:index, :new]
  get 'welcome/' => 'users#new'

  resources :groups, except: [:index, :new], shallow: true do
    resources :locations, except: [:index, :new]
  end

  root 'users#index'

end

app/models/group.rb
class Group
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :is_public, type: Mongoid::Boolean, default: true

  validates :name, presence: true
  validates_uniqueness_of :name, scope: :user_id

  validates :description, presence: true
  
  belongs_to :user
  has_many :locations, dependent: :destroy
end

app/models/location.rb
class Location
  include Mongoid::Document
  field :name, type: String
  field :address, type: String
  field :description, type: String

  validates :name, presence: true  
  validates :address, presence: true

  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  validates :name, presence: true
  validates :email, # presence: true, (unnecessary with below email validation)
            format: { with: /\A[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,10})\z/i },
            uniqueness: { case_sensitive: false }

  has_secure_password
  
  has_many :groups, dependent: :destroy
  has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Variables for navbar
  def header
    @has_navbar = true
    @user_login = User.new
    @is_login = true
  end

  # Variables for processing signup errors in render new
  def render_signup
    @groups = current_user.groups.all
    @location = Location.new
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :header, only: [:index, :create, :edit]
  before_action :render_signup, only: :create

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render 'users/index'
    end
  end

  def edit
    if current_user == Group.find(params[:id]).user
      @group = Group.find(params[:id])
      @form_btn = 'Save Changes'
    else
      redirect_to welcome_path
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    Group.find(params[:id]).destroy
    redirect_to root_path
  end

private

  def group_params
     params.require(:group).permit(:name, :description, :is_public)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  before_action :header, only: [:edit, :create]
  before_action :render_signup, only: :create

  def create
    # Attach group id to new location
    @group = Group.find(params[:group_id])
    @location = current_user.locations.new(location_params)
    @location.group = @group
    if @location.save
      redirect_to root_path
    else
      render 'users/index'
    end
  end

  def edit
    if current_user == Location.find(params[:id]).group.user
      @location = Location.find(params[:id])
      @group_options = current_user.groups.all.sort_by{ |alpha| alpha.name.downcase }.map{ |g| [ g.name, g.id ] }
      @form_btn = 'Save Changes'
    else
      redirect_to welcome_path
    end
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(location_params)
      redirect_to root_path
    else
      # render 'edit'
    end
  end

  def destroy
    Location.find(params[:id]).destroy
    redirect_to root_path
  end

private

  def location_params
    params.require(:location).permit(:name, :address, :description, :group_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.where(email: params[:user][:email]).first
    # Checks to see if the user exists, and then for a matching password
    if user && user.authenticate(params[:user][:password])
      # Creates a cookie for the user, holding the logged in user ID
      session[:user_id] = user.id.to_s
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  def destroy
    # Kill all of our cookies
    reset_session
    redirect_to welcome_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :header, except: [:update, :destroy]

  def index
    if current_user
      @groups = current_user.groups.all
      @group = current_user.groups.new
      @locations = @group.locations
      @location = Location.new
      @form_btn = 'Add'
      # render_location
    else
      redirect_to welcome_path
    end
  end

  def show
    # Alternative: @user = User.find_by(username: params[:id])
    @user = User.find(params[:id])
    @groups = @user.groups.all
  end

  def new
    @has_navbar = false
    @user = User.new
    @is_signup = true
  end

  def create
    # Variable for processing signup errors in render new
    @has_navbar = false
    @user = User.new(user_params)
    if @user.save
      # Login user after signup
      session[:user_id] = @user.id.to_s
      # Create default uncategorized group on signup
      current_user.groups.create(name: 'Uncategorized', description: 'Room to breathe', is_public: false)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    if current_user == User.find(params[:id])
      @user = current_user
    else
      redirect_to welcome_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    # Logout user before deleting account
    reset_session
    User.find(params[:id]).destroy
    redirect_to welcome_path
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<h2><%= @group.name %></h2>
<%= render 'partials/f.group' %>
  <br>
<%= link_to 'Delete', :group, method: :delete, data: { confirm: 'Are you sure you want to permanently delete this group?' } %>

app/views/groups/index.html.erb
<div style="color: red;">
  <h1>TESTING: GROUPS</h1>
  <h2>(delete groups#index later)</h2>
</div>

<!-- Display Groups List -->
<% @groups.sort_by{ |alpha| alpha.name.downcase }.each do |g| %>
<hr>
<div class="group">

  <!-- Display Group Name -->
  <h3><%= g.name %></h3>
  <h4><em><%= g.description %></em></h4>
  <%= link_to 'Edit', edit_group_path(g) %> /
  <%= link_to 'Delete', g, method: :delete, data: { confirm: "Permanently delete #{g.name}?" } %>

  <!-- Display Group Locations -->
  <ul class="locations">
  <% g.locations.sort_by{ |alpha| alpha.name.downcase }.each do |l| %>
    <li>
      <h4><%= l.name %></h4>
      <%= l.address %>
        <br>
      <em><%= l.description %></em>
        <br>
      <%= link_to 'Edit', edit_location_path(l) %> /
      <%= link_to 'Delete', l, method: :delete, data: { confirm: "Permanently delete #{l.name}?" } %>
    </li>
  <% end %>
  </ul>

    <br>

</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" data-ng-app="MapAddr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>MapAddr</title>
  <meta name="description" content="MapAddr Rails App.">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYt1gLYFIqYvB7ZSo5Fk272JIFvkizYIs"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>_controller" data-ng-controller="MapAddrController">

  <!-- Login -->
  <%= render 'partials/login' %>

  <!-- Navbar -->
  <%= render 'partials/navbar' %>
  
  <!-- Content -->
  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>

app/views/locations/edit.html.erb
<h4>Locations +</h4>
<%= form_for @location do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %><br>
  <%= f.text_field :address, placeholder: 'Address' %><br>
  <%= f.text_field :description, placeholder: 'Description' %><br>
  <%= f.select(:group_id, @group_options) %><br>
    <br>
  <%= f.submit 'Edit' %>
<% end %>

  <br>

<%= link_to 'Delete', @location, method: :delete, data: { confirm: 'Are you sure you want to permanently delete this location?' } %>

app/views/partials/_f.group.html.erb
<%= form_for @group do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %><br>
  <%= f.text_field :description, placeholder: 'Description' %><br>

  <%= f.label :is_public, 'Public' %>
  <%= f.radio_button :is_public, true %>

  <%= f.label :is_public, 'Private' %>
  <%= f.radio_button :is_public, false %>

    <br>
  <%= f.submit @form_btn %>
<% end %>

app/views/partials/_f.group.new.html.erb
<div class="modal fade" id="group" tabindex="-1" role="dialog" aria-labelledby="label-group" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="label-group">Create a group</h4>
      </div>
      <div class="modal-body">

        <%= form_for @group do |f| %>
          <div class="form-group">
            <%= f.text_field :name, placeholder: 'Name', id: 'focus-login', class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.text_field :description, placeholder: 'Description', class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :is_public, 'Public' %>
            <%= f.radio_button :is_public, true %>
              &nbsp;
            <%= f.label :is_public, 'Private' %>
            <%= f.radio_button :is_public, false %>
          </div>

          <%= f.submit @form_btn, class: 'btn btn-primary' %>
        <% end %>

      </div>
    </div>
  </div>
</div>

<script>
  $('#group').on('shown.bs.modal', function () {
    $('#focus-group').focus();
  });
</script>

app/views/partials/_f.location.new.html.erb
<% @groups.each do |g| %>
<div class="modal fade" id="location-<%= g.id %>" tabindex="-1" role="dialog" aria-labelledby="label-<%= g.id %>" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="label-<%= g.id %>">Add New Location</h4>
      </div>
      <div class="modal-body">

        <%= form_for [g, @location] do |f| %>
          <div class="form-group">
            <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.text_field :address, placeholder: 'Address', class: 'form-control', :'data-ng-model' => 'geoLoc' %>
          </div>

          <div class="form-group">
            <%= f.text_field :description, placeholder: 'Description (Optional)', class: 'form-control' %>
          </div>

          <button type="button" class="btn btn-primary" data-ng-click="currentLocation()"><i class="fa fa-crosshairs"></i>&nbsp; My Location</button>

          <%= f.submit 'Add', class: 'btn btn-primary' %>
        <% end %>

      </div>
    </div>
  </div>
</div>
<% end %>

app/views/partials/_login.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">MapAddr</h4>
      </div>
      <div class="modal-body">

        <%= form_for @user_login, { url: session_path } do |f| %>
          <div class="form-group">
            <%= f.text_field :email, placeholder: 'Email', id: 'focus-login', class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
          </div>
          <%= f.submit 'Login', class: 'btn btn-primary' %>
        <% end %>

      </div>
    </div>
  </div>
</div>

<script>
  $('#login').on('shown.bs.modal', function () {
    $('#focus-login').focus();
  });
</script>

app/views/partials/_navbar.html.erb
<% if @has_navbar %>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">

    <!-- Mobile Navbar Button -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'MapAddr', root_path, class: 'navbar-brand' %>
    </div>

    <ul class="nav navbar-nav navbar-left">
      <li>
        <!-- Search -->
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Find a location">
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>
      </li>

      <% if current_user %>
      <li>
        <button type="button" class="btn btn-default navbar-btn" data-toggle="modal" data-target="#group"><i class="fa fa-plus-square"></i>&nbsp; New Group</button>
      </li>
      <% end %>

    </ul>

    <!-- Collapse Toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <!-- Navbar Right -->
      <ul class="nav navbar-nav navbar-right">

        <!-- Logged In -->
        <% if current_user %>
        <li>
          <button type="button" class="btn btn-default navbar-btn" data-ng-click="locateMe()"><i class="fa fa-user"></i>&nbsp; <%= current_user.name %></button>
        </li>
        <li>&nbsp;</li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-gear"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Account', edit_user_path(current_user.id) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Log Out', session_path, method: :delete %></li>
          </ul>
        </li>
        <!-- Logged Out -->
        <% else %>
        <!-- Note: URL Path ends in '?'' -->
        <li><%= button_to 'Sign Up', welcome_path, method: :get, class: 'btn btn-default navbar-btn' %></li>
        <li><button type="submit" class="btn btn-default navbar-btn" data-toggle="modal" data-target="#login">Log In</button></li>
        <% end %>

      </ul> <!-- end navbar-right -->

    </div> <!-- end collapse -->

  </div> <!-- end container-fluid -->
</nav>
<% end %>

app/views/users/edit.html.erb
<h1>Account</h1>

<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %><br>
  <%= f.text_field :email, placeholder: 'Email' %><br>
  <%= f.password_field :password, placeholder: 'Password' %><br>
  <%= f.password_field :password_confirmation, placeholder: 'Confirm Password' %><br>
    <br>
  <%= f.submit 'Save Changes' %>
<% end %>

  <br>

<!-- Add TYPE DELETE TO CONFIRM -->
<%= link_to 'Delete Account', @user, method: :delete, data: { confirm: "Permanently delete this account?" } %>

app/views/users/index.html.erb
<!-- Modals -->
<%= render 'partials/f.group.new' %>
<%= render 'partials/f.location.new' %>

<!-- Main View -->
<div class="row">
  <div class="dashboard col-md-2">
    <br>
    <!-- Display Groups List -->
    <div class="panel-group" id="accordion">
    <% @groups.sort_by{ |alpha| alpha.name.downcase }.each do |g| %>

      <!-- Display Group -->
      <div class="panel panel-default">

        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#<%= g.id %>">
              <h3><%= g.name %></h3>
              <p><%= g.description %></p>
            </a>
          </h4>

          <!-- Add Group Location Form -->
          <span class="location" data-toggle="modal" data-target="#location-<%= g.id %>"><i class="fa fa-map-marker"></i> New</span> /

          <%= link_to 'Edit', edit_group_path(g) %> /
          <%= link_to 'Delete', g, method: :delete, data: { confirm: "Permanently delete #{g.name}?" } %>
        </div>

        <!-- Display Locations -->
        <div id="<%= g.id %>" class="panel-collapse collapse in">
          <div class="panel-body">

            <!-- Display Group Locations -->
            <% g.locations.sort_by{ |alpha| alpha.name.downcase }.each do |l| %>
              <section class="location" data-ng-init="codeAddress('<%= l.address %>', '<%= l.name %>')" data-ng-click="calcRoute('<%= l.address %>', '<%= l.name %>')">
                <p class="name"><strong><%= l.name %></strong></p>
                <p class="desc"><em><%= l.description %></em></p>
              </section>
              <section class="meta-location">
                <%= link_to 'Edit', edit_location_path(l) %> /
                <%= link_to 'Delete', l, method: :delete, data: { confirm: "Permanently delete #{l.name}?" } %>
              </section>
            <% end %>

          </div> <!-- end panel-body -->
        </div> <!-- end panel-collapse -->
      </div> <!-- end panel -->
    <% end %>
    </div> <!-- end panel-group -->

  </div> <!-- end dashboard-->

  <!-- Map -->
  <div class="map col-md-10 col-md-offset-2">
    <div id="directionsPanel" style="float:right;width:30%;height 100%"></div>
    <div id="map-canvas"></div>
  </div>

</div> <!-- end row -->

<!-- Alert Errors -->
<% if @group.errors.any? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4>Oops, made a wrong turn!</h4>
    <% @group.errors.full_messages.each do |msg| %>
      <p><%= msg %> for group</p>
    <% end %>
  </div>
<% end %>

<% if @location.errors.any? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4>Oops, made a wrong turn!</h4>
    <% @location.errors.full_messages.each do |msg| %>
      <p><%= msg %> for location</p>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<!-- Welcome Background -->
<div class="welcome">

  <!-- Sign Up -->
  <section class="sign-up">

    <h1>MapAddr</h1>
    <p>Group and share your locations.</p>
    <%= form_for @user, html: { role: 'form' } do |f| %>
      <div class="form-group">
        <%= f.text_field :name, placeholder: 'Name', class: 'form-control', autofocus: true %>
        <%= f.text_field :email, placeholder: 'Email', class: 'form-control' %>
        <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
        <%= f.password_field :password_confirmation, placeholder: 'Retype Password', class: 'form-control' %>
      </div>
      <%= f.submit 'SIGN UP', class: 'btn btn-default' %>
    <% end %>

    <!-- Login -->
    <div class="login-link">
      <p>Already have an account?</p>
      <p><a data-toggle="modal" data-target="#login">Log In</a></p>
    </div>

  </section>

</div>

<!-- Alert Errors -->
<% if @user.errors.any? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4>Oops, wrong way!</h4>
    <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>

app/views/users/show.html.erb
<!-- Display User Name -->
<h1><%= @user.name %>'s Addrs</h1>

<!-- Display Groups List -->
<% @groups.sort_by{ |alpha| alpha.name.downcase }.each do |g| %>
  <% if g.is_public %>
  <hr>
  <div class="group">

    <!-- Display Group Name -->
    <h3><%= g.name %></h3>
    <h4><em><%= g.description %></em></h4>

    <!-- Display Group Locations -->
    <ul class="locations">
    <% g.locations.sort_by{ |alpha| alpha.name.downcase }.each do |l| %>
      <li>
        <h4><%= l.name %></h4>
        <%= l.address %>
          <br>
        <em><%= l.description %></em>
          <br>
      </li>
    <% end %>
    </ul>

      <br>

  </div>
  <% end %>
<% end %>